@php($assessment ??= null)
<section class="rounded-lg border border-zinc-200 bg-white p-5 shadow-xs dark:border-zinc-700 dark:bg-zinc-900">
    <div class="grid gap-5 md:grid-cols-2">
        <div><label class="text-sm font-medium" for="class_schedule_id">{{ __('Class Schedule') }}</label><select id="class_schedule_id" name="class_schedule_id" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('Select class') }}</option>@foreach($classSchedules as $schedule)<option value="{{ $schedule->id }}" @selected((int) old('class_schedule_id', $assessment->class_schedule_id ?? 0) === $schedule->id)>{{ $schedule->schoolYear->name }} · {{ $schedule->subject->code }} · {{ $schedule->section->code }}</option>@endforeach</select>@error('class_schedule_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium" for="grading_period_id">{{ __('Grading Period') }}</label><select id="grading_period_id" name="grading_period_id" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('Select period') }}</option>@foreach($gradingPeriods as $period)<option value="{{ $period->id }}" @selected((int) old('grading_period_id', $assessment->grading_period_id ?? 0) === $period->id)>{{ $period->schoolYear->name }} · {{ $period->name }}</option>@endforeach</select>@error('grading_period_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium" for="title">{{ __('Title') }}</label><input id="title" name="title" value="{{ old('title', $assessment->title ?? '') }}" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('title')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium" for="assessment_type">{{ __('Type') }}</label><input id="assessment_type" name="assessment_type" value="{{ old('assessment_type', $assessment->assessment_type ?? '') }}" class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"></div>
        <div><label class="text-sm font-medium" for="max_score">{{ __('Max Score') }}</label><input id="max_score" name="max_score" type="number" step="0.01" min="0.01" value="{{ old('max_score', $assessment->max_score ?? 100) }}" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('max_score')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium" for="weight">{{ __('Weight') }}</label><input id="weight" name="weight" type="number" step="0.01" min="0" value="{{ old('weight', $assessment->weight ?? 0) }}" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('weight')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-medium" for="due_date">{{ __('Due Date') }}</label><input id="due_date" name="due_date" type="date" value="{{ old('due_date', optional($assessment?->due_date ?? null)->format('Y-m-d')) }}" class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"></div>
        <div><label class="text-sm font-medium" for="status">{{ __('Status') }}</label><select id="status" name="status" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $assessment->status ?? \App\Models\Assessment::STATUS_DRAFT) === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
        <div class="md:col-span-2"><label class="text-sm font-medium" for="notes">{{ __('Notes') }}</label><textarea id="notes" name="notes" rows="3" class="mt-1 w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-950">{{ old('notes', $assessment->notes ?? '') }}</textarea></div>
    </div>
    <div class="mt-6 flex gap-3"><flux:button type="submit" variant="primary">{{ $submit }}</flux:button><flux:button :href="route('grades.assessments.index')" wire:navigate>{{ __('Cancel') }}</flux:button></div>
</section>
