<x-layouts::app :title="__('Assessments')">
    <div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-6">
        <div class="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><flux:heading size="xl">{{ __('Assessments') }}</flux:heading><flux:subheading>{{ __('Manage class assessments and grade entry targets.') }}</flux:subheading></div>@can('grades.create')<flux:button :href="route('grades.assessments.create')" wire:navigate variant="primary">{{ __('Create Assessment') }}</flux:button>@endcan</div>
        <section class="rounded-lg border border-zinc-200 bg-white shadow-xs dark:border-zinc-700 dark:bg-zinc-900">
            <form method="GET" action="{{ route('grades.assessments.index') }}" class="grid gap-3 border-b border-zinc-200 p-4 dark:border-zinc-700 md:grid-cols-[1fr_220px_220px_160px_auto]">
                <div></div>
                <select name="grading_period_id" class="h-10 rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('All periods') }}</option>@foreach($gradingPeriods as $period)<option value="{{ $period->id }}" @selected((int) request('grading_period_id') === $period->id)>{{ $period->name }}</option>@endforeach</select>
                <select name="class_schedule_id" class="h-10 rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('All classes') }}</option>@foreach($classSchedules as $schedule)<option value="{{ $schedule->id }}" @selected((int) request('class_schedule_id') === $schedule->id)>{{ $schedule->subject->code }} · {{ $schedule->section->code }}</option>@endforeach</select>
                <select name="status" class="h-10 rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('All statuses') }}</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select>
                <flux:button type="submit">{{ __('Filter') }}</flux:button>
            </form>
            <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-zinc-200 text-xs uppercase text-zinc-500 dark:border-zinc-700 dark:text-zinc-400"><tr><th class="px-4 py-3">{{ __('Assessment') }}</th><th class="px-4 py-3">{{ __('Class') }}</th><th class="px-4 py-3">{{ __('Max') }}</th><th class="px-4 py-3">{{ __('Status') }}</th><th class="px-4 py-3 text-right">{{ __('Actions') }}</th></tr></thead>
                <tbody class="divide-y divide-zinc-200 dark:divide-zinc-800">@forelse($assessments as $assessment)<tr><td class="px-4 py-4"><p class="font-medium">{{ $assessment->title }}</p><p class="text-zinc-500">{{ $assessment->gradingPeriod->name }}</p></td><td class="px-4 py-4">{{ $assessment->classSchedule->subject->code }} · {{ $assessment->classSchedule->section->code }}</td><td class="px-4 py-4">{{ $assessment->max_score }}</td><td class="px-4 py-4"><x-records.partials.status-badge :status="$assessment->status" /></td><td class="px-4 py-4 text-right"><div class="flex justify-end gap-2"><flux:button size="sm" :href="route('grades.assessments.records', $assessment)" wire:navigate>{{ __('Records') }}</flux:button><flux:button size="sm" :href="route('grades.assessments.show', $assessment)" wire:navigate>{{ __('View') }}</flux:button>@can('grades.update')<flux:button size="sm" :href="route('grades.assessments.edit', $assessment)" wire:navigate>{{ __('Edit') }}</flux:button>@endcan</div></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-zinc-500">{{ __('No assessments found.') }}</td></tr>@endforelse</tbody>
            </table></div><div class="border-t border-zinc-200 p-4 dark:border-zinc-700">{{ $assessments->links() }}</div>
        </section>
    </div>
</x-layouts::app>
