@php($gradingPeriod ??= null)
<section class="rounded-lg border border-zinc-200 bg-white p-5 shadow-xs dark:border-zinc-700 dark:bg-zinc-900">
    <div class="grid gap-5 md:grid-cols-2">
        <div><label for="school_year_id" class="text-sm font-medium">{{ __('School Year') }}</label><select id="school_year_id" name="school_year_id" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('Select school year') }}</option>@foreach($schoolYears as $schoolYear)<option value="{{ $schoolYear->id }}" @selected((int) old('school_year_id', $gradingPeriod->school_year_id ?? 0) === $schoolYear->id)>{{ $schoolYear->name }}</option>@endforeach</select>@error('school_year_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="status" class="text-sm font-medium">{{ __('Status') }}</label><select id="status" name="status" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $gradingPeriod->status ?? \App\Models\GradingPeriod::STATUS_ACTIVE) === $status)>{{ str($status)->headline() }}</option>@endforeach</select>@error('status')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="name" class="text-sm font-medium">{{ __('Name') }}</label><input id="name" name="name" value="{{ old('name', $gradingPeriod->name ?? '') }}" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="sort_order" class="text-sm font-medium">{{ __('Sort Order') }}</label><input id="sort_order" name="sort_order" type="number" min="1" value="{{ old('sort_order', $gradingPeriod->sort_order ?? 1) }}" required class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('sort_order')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="starts_at" class="text-sm font-medium">{{ __('Start Date') }}</label><input id="starts_at" name="starts_at" type="date" value="{{ old('starts_at', optional($gradingPeriod?->starts_at ?? null)->format('Y-m-d')) }}" class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('starts_at')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div><label for="ends_at" class="text-sm font-medium">{{ __('End Date') }}</label><input id="ends_at" name="ends_at" type="date" value="{{ old('ends_at', optional($gradingPeriod?->ends_at ?? null)->format('Y-m-d')) }}" class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error('ends_at')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    </div>
    <div class="mt-6 flex gap-3"><flux:button type="submit" variant="primary">{{ $submit }}</flux:button><flux:button :href="route('grades.grading-periods.index')" wire:navigate>{{ __('Cancel') }}</flux:button></div>
</section>
