<x-layouts::app :title="__('Enter Grades')">
    <div class="mx-auto flex w-full max-w-7xl flex-1 flex-col gap-6 p-6">
        <div><flux:heading size="xl">{{ __('Enter Grades') }}</flux:heading><flux:subheading>{{ $assessment->title }} · {{ $assessment->classSchedule->section->code }}</flux:subheading></div>
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
        <form method="POST" action="{{ route('teacher.grades.assessments.save', $assessment) }}" class="rounded-lg border border-zinc-200 bg-white shadow-xs dark:border-zinc-700 dark:bg-zinc-900">
            @csrf
            <div class="grid gap-4 border-b border-zinc-200 p-5 dark:border-zinc-700 md:grid-cols-[180px_1fr]"><div><label class="text-sm font-medium" for="grade_status">{{ __('Save As') }}</label><select id="grade_status" name="grade_status" class="mt-1 h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($statuses as $status)<option value="{{ $status }}">{{ str($status)->headline() }}</option>@endforeach</select></div><div class="text-sm text-zinc-500">{{ __('Max score') }}: {{ $assessment->max_score }}</div></div>
            <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-zinc-200 text-xs uppercase text-zinc-500 dark:border-zinc-700 dark:text-zinc-400"><tr><th class="px-5 py-3">{{ __('Student') }}</th><th class="px-5 py-3">{{ __('Score') }}</th><th class="px-5 py-3">{{ __('Remarks') }}</th></tr></thead>
                <tbody class="divide-y divide-zinc-200 dark:divide-zinc-800">@forelse($students as $index => $student)@php($grade = $gradesByStudent->get($student->id))<tr><td class="px-5 py-4"><input type="hidden" name="grades[{{ $index }}][student_id]" value="{{ $student->id }}"><p class="font-medium">{{ $student->fullName() }}</p><p class="text-zinc-500">{{ $student->student_number }}</p></td><td class="px-5 py-4"><input name="grades[{{ $index }}][score]" type="number" step="0.01" min="0" max="{{ $assessment->max_score }}" value="{{ old("grades.$index.score", $grade->score ?? '') }}" class="h-10 rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950">@error("grades.$index.score")<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</td><td class="px-5 py-4"><input name="grades[{{ $index }}][remarks]" value="{{ old("grades.$index.remarks", $grade->remarks ?? '') }}" class="h-10 w-full rounded-md border border-zinc-300 bg-white px-3 text-sm dark:border-zinc-700 dark:bg-zinc-950"></td></tr>@empty<tr><td colspan="3" class="px-5 py-10 text-center text-zinc-500">{{ __('No enrolled students found.') }}</td></tr>@endforelse</tbody>
            </table></div><div class="border-t border-zinc-200 p-5 dark:border-zinc-700"><flux:button type="submit" variant="primary">{{ __('Save Grades') }}</flux:button></div>
        </form>
    </div>
</x-layouts::app>
